import pandas as pd
import streamlit as st
from pymongo import MongoClient

# Page Setup
st.set_page_config(page_title="Learned Trades Dashboard", page_icon="🤖", layout="wide")

st.title("🤖 Learned Model Trade Performance")
st.write("Sequential BUY and EXIT trade pairings generated by the learned model.")


# Initialize MongoDB connection (Cached)
@st.cache_resource
def init_connection():
    mongo_uri = st.secrets["mongo"]["uri"]
    return MongoClient(mongo_uri)


client = init_connection()
db = client[st.secrets["mongo"]["db_name"]]
collection = db[st.secrets["mongo"]["collection_name"]]


# Fetch and pair learned trades chronologically
@st.cache_data(ttl=300)
def load_paired_learned_trades():
    documents = list(collection.find({}))
    all_paired_trades = []

    for doc in documents:
        symbol = doc.get("symbol")
        learned_records = []

        # Extract all learned records from the trades array
        for t in doc.get("trades", []):
            if "learned" in t and t["learned"]:
                l = t["learned"]
                l["symbol"] = symbol
                learned_records.append(l)

        if not learned_records:
            continue

        # Load into Pandas and sort chronologically to handle multi-day gaps
        df_symbol = pd.DataFrame(learned_records)
        if "timestamp" not in df_symbol.columns:
            continue

        df_symbol["timestamp"] = pd.to_datetime(df_symbol["timestamp"])
        df_symbol = df_symbol.sort_values("timestamp").reset_index(drop=True)

        # Pair BUY with the subsequent EXIT sequentially
        current_buy = None
        for _, row in df_symbol.iterrows():
            action = row.get("action")

            if action == "BUY":
                current_buy = row
            elif action == "EXIT" and current_buy is not None:
                entry_price = current_buy.get("entry_price")
                # Fallback to row price if exit_price is stored differently
                exit_price = row.get("exit_price") or row.get("entry_price")

                pnl_pct = None
                if entry_price and exit_price and entry_price > 0:
                    pnl_pct = (exit_price - entry_price) / entry_price

                all_paired_trades.append(
                    {
                        "symbol": symbol,
                        "entry_timestamp": current_buy["timestamp"].strftime(
                            "%Y-%m-%d %H:%M"
                        ),
                        "exit_timestamp": row["timestamp"].strftime("%Y-%m-%d %H:%M"),
                        "entry_price": entry_price,
                        "exit_price": exit_price,
                        "pnl_pct": pnl_pct,
                        "expected_reward": current_buy.get("expected_reward"),
                        "conviction_score": current_buy.get("features", {}).get(
                            "conviction_score"
                        ),
                    }
                )
                current_buy = None  # Reset for the next trade cycle

    return pd.DataFrame(all_paired_trades)


df = load_paired_learned_trades()

if df.empty:
    st.warning("No paired learned trade records found in MongoDB.")
else:
    # Sidebar Filters
    st.sidebar.header("Filter Options")

    all_symbols = sorted(df["symbol"].dropna().unique())
    selected_symbols = st.sidebar.multiselect(
        "Select Symbol(s)", options=all_symbols, default=all_symbols
    )

    # Apply filtering
    filtered_df = df[df["symbol"].isin(selected_symbols)]

    # Summary Metrics
    total_trades = len(filtered_df)
    valid_pnl = filtered_df["pnl_pct"].dropna()
    win_rate = (valid_pnl > 0).mean() * 100 if not valid_pnl.empty else 0.0
    avg_pnl = valid_pnl.mean() * 100 if not valid_pnl.empty else 0.0

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Round-Trip Trades", total_trades)
    col2.metric("Unique Symbols", filtered_df["symbol"].nunique())
    col3.metric("Win Rate", f"{win_rate:.1f}%")
    col4.metric("Avg PnL %", f"{avg_pnl:.2f}%")

    # Interactive Table Grid
    st.subheader("Learned Trade Pairings (BUY ➔ EXIT)")

    # Format columns for visual nicety if data exists
    display_df = filtered_df.copy()
    if "pnl_pct" in display_df.columns:
        display_df["pnl_pct"] = display_df["pnl_pct"].apply(
            lambda x: f"{x * 100:.2f}%" if pd.notnull(x) else "N/A"
        )

    st.dataframe(display_df, use_container_width=True)
