import pandas as pd
import streamlit as st
from pymongo import MongoClient

# -----------------------------
# Page Setup
# -----------------------------
st.set_page_config(page_title="Learned Trades Dashboard", page_icon="🤖", layout="wide")

st.title("🤖 Learned Model Trade Performance")
st.write("Sequential BUY and EXIT trade pairings generated by the learned model.")

position_size = 100

# -----------------------------
# MongoDB Connection (cached)
# -----------------------------
@st.cache_resource
def init_connection():
    mongo_uri = st.secrets["mongo"]["uri"]
    return MongoClient(mongo_uri)

client = init_connection()
db = client[st.secrets["mongo"]["db_name"]]
collection = db[st.secrets["mongo"]["collection_name"]]


# -----------------------------
# Load learned trades via aggregation (FAST)
# -----------------------------
@st.cache_data(ttl=300)
def load_flat_learned_trades() -> pd.DataFrame:
    pipeline = [
        {"$unwind": "$trades"},
        {"$match": {"trades.learned": {"$exists": True}}},
        {
            "$project": {
                "symbol": 1,
                "timestamp": "$trades.timestamp",
                "action": "$trades.learned.action",
                "entry_price": "$trades.learned.entry_price",
                "exit_price": "$trades.learned.exit_price",
                "expected_reward": "$trades.learned.expected_reward",
                "features": "$trades.learned.features",
            }
        },
        {"$sort": {"symbol": 1, "timestamp": 1}},
    ]

    docs = list(collection.aggregate(pipeline))
    if not docs:
        return pd.DataFrame()

    df = pd.DataFrame(docs)
    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])

    return df


# -----------------------------
# Pair BUY/EXIT trades (vectorized)
# -----------------------------
@st.cache_data(ttl=300)
def pair_learned_trades() -> pd.DataFrame:
    df = load_flat_learned_trades()
    if df.empty:
        return df

    # Ensure required columns exist
    required_cols = {"symbol", "timestamp", "action", "entry_price", "exit_price"}
    if not required_cols.issubset(df.columns):
        return pd.DataFrame()

    # Sort by symbol + time
    df = df.sort_values(["symbol", "timestamp"]).reset_index(drop=True)

    # Shift next row per symbol to pair BUY with next EXIT
    df["next_action"] = df.groupby("symbol")["action"].shift(-1)
    df["next_exit_price"] = df.groupby("symbol")["exit_price"].shift(-1)
    df["next_timestamp"] = df.groupby("symbol")["timestamp"].shift(-1)

    # Filter BUY rows whose next action is EXIT
    paired = df[(df["action"] == "BUY") & (df["next_action"] == "EXIT")].copy()

    # Compute PnL
    valid_mask = paired["entry_price"].notnull() & paired["next_exit_price"].notnull() & (paired["entry_price"] > 0)
    paired.loc[valid_mask, "pnl_pct"] = (
        (paired.loc[valid_mask, "next_exit_price"] - paired.loc[valid_mask, "entry_price"])
        / paired.loc[valid_mask, "entry_price"]
    )
    paired.loc[valid_mask, "profit_amount"] = (
        (paired.loc[valid_mask, "next_exit_price"] - paired.loc[valid_mask, "entry_price"])
        * position_size
    )

    # Conviction score from features if present
    def extract_conviction(feat):
        if isinstance(feat, dict):
            return feat.get("conviction_score")
        return None

    paired["conviction_score"] = paired["features"].apply(extract_conviction)

    # Final display frame
    result = pd.DataFrame(
        {
            "symbol": paired["symbol"],
            "entry_timestamp": paired["timestamp"].dt.strftime("%Y-%m-%d %H:%M"),
            "exit_timestamp": paired["next_timestamp"].dt.strftime("%Y-%m-%d %H:%M"),
            "entry_price": paired["entry_price"],
            "exit_price": paired["next_exit_price"],
            "profit amount($)": round(paired["profit_amount"],2),
            "pnl_pct": paired["pnl_pct"],
            "expected_reward": paired["expected_reward"],
            "conviction_score": paired["conviction_score"],
        }
    )

    # Newest first
    result = result.sort_values("entry_timestamp", ascending=False).reset_index(drop=True)
    return result


# -----------------------------
# Main UI
# -----------------------------
df = pair_learned_trades()

if df.empty:
    st.warning("No paired learned trade records found in MongoDB.")
else:
    # Sidebar Filters
    st.sidebar.header("Filter Options")

    all_symbols = sorted(df["symbol"].dropna().unique())
    selected_symbols = st.sidebar.multiselect(
        "Select Symbol(s)", options=all_symbols, default=all_symbols
    )

    filtered_df = df[df["symbol"].isin(selected_symbols)]

    # Summary Metrics
    total_trades = len(filtered_df)
    valid_pnl = filtered_df["pnl_pct"].dropna()
    win_rate = (valid_pnl > 0).mean() * 100 if not valid_pnl.empty else 0.0
    avg_pnl = valid_pnl.mean() * 100 if not valid_pnl.empty else 0.0

    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Total Round-Trip Trades", total_trades)
    col2.metric("Unique Symbols", filtered_df["symbol"].nunique())
    col3.metric("Win Rate", f"{win_rate:.1f}%")
    col4.metric("Avg PnL %", f"{avg_pnl:.2f}%")
    col5.metric("Position Size", f"{position_size}")

    # Table
    st.subheader("Learned Trade Pairings (Newest First)")

    display_df = filtered_df.copy()
    if "pnl_pct" in display_df.columns:
        display_df["pnl_pct"] = display_df["pnl_pct"].apply(
            lambda x: f"{x * 100:.2f}%" if pd.notnull(x) else "N/A"
        )

    st.dataframe(display_df, use_container_width=True)
