import pandas as pd
import streamlit as st
from pymongo import MongoClient

# -----------------------------
# Page Setup
# -----------------------------
st.set_page_config(
    page_title="Quantitative Backtest Dashboard", page_icon="⚡", layout="wide"
)

st.title("⚡ Quantitative Backtest Performance Dashboard")
st.write(
    "Simulated trade ledger generated by the ATR Risk/Reward Model and Trade"
    " Manager."
)

position_size = st.sidebar.number_input(
    "Position Size ($)", value=1000, step=100
)
initial_capital = st.sidebar.number_input(
    "Initial Capital ($)", value=50000, step=5000
)


# -----------------------------
# MongoDB Connection (cached)
# -----------------------------
@st.cache_resource
def init_connection():
  mongo_uri = st.secrets["mongo"]["uri"]
  return MongoClient(mongo_uri)


client = init_connection()
db = client[st.secrets["mongo"]["db_name"]]
trades_collection = db["backtest_trades"]


# -----------------------------
# Load Backtest Trades from MongoDB (FAST)
# -----------------------------
@st.cache_data(ttl=300)
def load_backtest_trades() -> pd.DataFrame:
  docs = list(trades_collection.find({}, {"_id": 0}))
  if not docs:
    return pd.DataFrame()

  df = pd.DataFrame(docs)
  if "execution_date" in df.columns:
    df["execution_date"] = pd.to_datetime(df["execution_date"])
  if "signal_date" in df.columns:
    df["signal_date"] = pd.to_datetime(df["signal_date"])

  return df


# -----------------------------
# Main UI & Filtering
# -----------------------------
df = load_backtest_trades()

if df.empty:
  st.warning(
      "⚠️ No backtest trade records found in MongoDB collection"
      " 'backtest_trades'. Run your Redis backtest engine first."
  )
else:
  st.sidebar.header("Filter Options")

  all_symbols = sorted(df["symbol"].dropna().unique())
  selected_symbols = st.sidebar.multiselect(
      "Select Symbol(s)", options=all_symbols, default=all_symbols
  )

  all_outcomes = sorted(df["outcome"].dropna().unique())
  selected_outcomes = st.sidebar.multiselect(
      "Select Exit Outcome(s)", options=all_outcomes, default=all_outcomes
  )

  filtered_df = df[
      df["symbol"].isin(selected_symbols) & df["outcome"].isin(selected_outcomes)
  ].sort_values("execution_date", ascending=True)

  if filtered_df.empty:
    st.warning("No trades match the selected filters.")
  else:
    # Calculate dollar profit amounts based on PnL % and position size
    filtered_df["profit_amount"] = filtered_df["pnl_pct"] * position_size

    # Summary Metrics Calculations
    total_trades = len(filtered_df)
    valid_pnl = filtered_df["pnl_pct"].dropna()
    win_rate = (valid_pnl > 0).mean() * 100 if not valid_pnl.empty else 0.0
    avg_pnl = valid_pnl.mean() * 100 if not valid_pnl.empty else 0.0

    chron_df = filtered_df.sort_values("execution_date").reset_index(drop=True)
    profits = chron_df["profit_amount"].fillna(0)
    capital_curve = initial_capital + profits.cumsum()

    total_profit = profits.sum()
    ending_capital = (
        capital_curve.iloc[-1] if len(capital_curve) else initial_capital
    )

    rolling_max = capital_curve.cummax()
    drawdown = capital_curve - rolling_max
    max_drawdown = drawdown.min()
    max_drawdown_pct = (
        (max_drawdown / rolling_max.max()) * 100
        if rolling_max.max() > 0
        else 0
    )

    # -----------------------------
    # Display Metrics Grid
    # -----------------------------
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Total Trades", total_trades)
    col2.metric("Unique Symbols", filtered_df["symbol"].nunique())
    col3.metric("Win Rate", f"{win_rate:.1f}%")
    col4.metric("Avg PnL %", f"{avg_pnl:.2f}%")
    col5.metric("Position Size", f"${position_size:,}")

    col6, col7, col8 = st.columns(3)
    col6.metric("Total Profit (\()", f"\){total_profit:,.2f}")
    col7.metric("Ending Capital (\()", f"\){ending_capital:,.2f}")
    col8.metric("Max Drawdown (%)", f"{max_drawdown_pct:.2f}%")

    # -----------------------------
    # Equity Curve Chart
    # -----------------------------
    st.subheader("📈 Strategy Equity Curve (Capital Over Time)")

    equity_df = pd.DataFrame({
        "timestamp": chron_df["execution_date"],
        "capital": capital_curve,
    })

    st.line_chart(equity_df.set_index("timestamp"))

    # -----------------------------
    # Trade Ledger Table
    # -----------------------------
    st.subheader("📋 Simulated Trades Ledger (Chronological)")

    display_df = filtered_df.copy()
    if "pnl_pct" in display_df.columns:
      display_df["pnl_pct"] = display_df["pnl_pct"].apply(
          lambda x: f"{x * 100:.2f}%" if pd.notnull(x) else "N/A"
      )

    st.dataframe(display_df, use_container_width=True)
